import './globals.css';
import type { Metadata } from 'next';
import { Tektur } from 'next/font/google';

import Providers from './providers';

import { Header } from '@/components';

const tektur = Tektur({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }): JSX.Element {
  return (
    <html lang="en">
      <body className={tektur.className}>
        <Header />
        <Providers>
          <main className="app-layout">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
