on: pull_request

name: Continuous Integration

jobs:
  coverage_report:
    name: Generate coverage report
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - name: Install dependencies
      run: pnpm install

    - name: Generate LCOV
      run: pnpm test

    - name: Read Report File
        id: file-content
        run: |
          content=$(cat coverage/coverage.txt)
          echo "::set-output name=content::$content"

    - name: LCOV comment
    - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const issueNumber = context.issue.number;
            const content = `$(cat coverage/coverage.txt)`;
            const body = `
            Coverage report:
            \`\`\`
            ${content}
            \`\`\`
            `;
            github.rest.issues.createComment({
              issue_number: issueNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });

    - name: Report code coverage
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        file: ./coverage/apps/portal-spa/lcov.info
        compare-ref: main