on: pull_request

name: Continuous Integration

jobs:
  coverage_report:
    name: Generate coverage report
    runs-on: ubuntu-latest
    steps:
    - uses: pnpm/action-setup@v2
      with:
        version: 7.9.3

    - name: install NPM dependencies
      run: pnpm i

    - name: Generate LCOV
      run: pnpm test

    - name: Report code coverage
      uses: zgosalvez/github-actions-report-lcov@v3
      with:
        coverage-files: coverage/lcov.*.info
        minimum-coverage: 90
        artifact-name: code-coverage-report
        github-token: ${{ secrets.GITHUB_TOKEN }}
        working-directory: apps/my-first-app
        update-comment: true