on: pull_request

name: Continuous Integration

jobs:
  coverage_report:
    name: Generate coverage report
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - name: Install dependencies
      run: pnpm install

    - name: Generate LCOV
      run: pnpm test

    - name: Publish test coverage report
      uses: actions/github-script@v7
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const fs = require('fs');
          const summaryContent = fs.readFileSync('./coverage/summary.txt', 'utf8');
          const coverageContent = fs.readFileSync('./coverage/coverage.txt', 'utf8');
          const issueNumber = context.issue.number;

          await github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `${ summaryContent }
            
            ${ coverageContent.split('\n').map((line) => "|" + line + "|").join() }`
          })
