on: pull_request

name: Continuous Integration

jobs:
  coverage_report:
    name: Generate coverage report
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - name: Install dependencies
      run: pnpm install

    - name: Generate LCOV
      run: pnpm test

    - name: Find Comment
      uses: peter-evans/find-comment@v2
      id: fc
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
        body-includes: Coverage summary

    - name: Publish test coverage report
      uses: peter-evans/create-or-update-comment@v3
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        comment-id: ${{ steps.fc.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        body-path: './coverage/report.md'
        edit-mode: replace
        
